#!/usr/bin/env bash
# This script kills the 7-highlander process using SIGKILL (signal 9)

# Get the PID of the 7-highlander script
PID=$(pgrep -f 7-highlander)

# Send SIGKILL (signal 9)
[ -n "$PID" ] && kill -9 "$PID"

